[build]
  command = "npm run build"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/check-email"
  to = "/.netlify/functions/check-email"
  status = 200
